'use strict'

try{
    let x = 10;
    //miFuncion();
}

catch (error){
    console.log(error);
}
    
finally{ // Bloque opcional
    console.log('termina la revision de errores')
}
console.log('continuamos...') // cuando surge un error la ejecuci√≥n se detiene y no continua con las siguientes lineas

    
